[WIP] Formula Bar
mito-ds/monorepo pull request #222
Opened 2022-04-07 19:32 UTC by aarondr77

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context, and the specification if there is one. 

# Testing

Please provide a list of the ways you can "access" or use the functionality. Please try and be exhaustive here, and make sure that you test everything you list.

- [ ] I have tested this on real data that is reasonable and large
- [ ] If I changed the interaction with JupyterLab, I tested that it does not break other programs (like VS Code), and tested that it works "multiple times" in the same notebook.

# Documentation

Note if any new documentation needs to addressed or reviewed.

2022-04-08 02:14 UTC, aarondr77 commented on mitosheet/css/endo/CellEditor.css
> +    height: 26px;
Add a comment that this is 26px so that it lines up with the formula bar

2022-04-08 02:14 UTC, aarondr77 commented on mitosheet/src/components/endo/CellEditor.tsx
> +    console.log(props.containerRef)
remove

2022-04-08 02:14 UTC, aarondr77 commented on mitosheet/src/components/endo/CellEditor.tsx
> +            console.log('here')
remove

2022-04-08 02:14 UTC, aarondr77 commented on mitosheet/css/sitewide/flexbox.css
> +    align-items: center;
Ended up not using this, remove it

2022-04-08 12:00 UTC, naterush requested changes
I think trying to reuse the exact same component for both the cell editor and the formula bar is probably a loosing game - given that we want the former to float about, and the latter to be fixed in place. I think a floating look in the second case is bad news bears.

A cleaner way to approach this probably:
1. Take the `CellEditor` and split it into a `CellEditorInput` and `FloatingCellEditor`. The `CellEditorInput` is the `form` component and all it's children (I think), and all the logic for using the arrow keys to navigate about (and all the focus handling). The `CellEditorInput` fills it's container.
2. The `FloatingCellEditor` wraps the `CellEditorInput` and moves it about - so pretty much just the code of the `CellEditor` currently!
3. Then, create a `FormulaBarCellEditor`. It does not float, but also has the `CellEditorInput` as a child component. 

Thoughts? I might be missing something on why this is bad - but you end up with a floating thing sometimes and not others, without pretty much any duplicated code...

2022-04-08 12:54 UTC, naterush commented
@aarondr77 I think we went into the implementation phase of this story a bit too quickly. We've been avoiding this story for a while based on technical complexity - and although we addressed a lot of that with the removal of Endo, the fact that we paused in the past should cause us to take the time to write a little spec. The triggers for writing a spec is: big feature OR small feature + someone thinks it might be scary.

I don't think it had to be much - but if you had written up this proposed approach, I probably would have been able to give some input about floating elements being fragile earlier - which could have saved you/us some time!

No big deal, just a lesson learned for the future :-)

2022-04-08 14:06 UTC, aarondr77 commented
One issue with your proposal is that we do want parts of the cell editor to be floating -- the dropdown box should float about the grid. So if we break it out, then we will have to add back the floating of just the dropdown box.

2022-04-09 01:16 UTC, aarondr77 commented
Leaving a note here so I don't forget. We're going takes Nate's proposal + break the cell editor input and the dropdown box into separate components so that we can leave the cell editor input as a placed item of its parent, and make the dropdown box foat

2022-04-19 20:45 UTC, closed without merging