Fix rename
mito-ds/monorepo pull request #536
Opened 2022-11-20 19:34 UTC by aarondr77

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context, and the specification if there is one. 

# Testing

Please provide a list of the ways you can "access" or use the functionality. Please try and be exhaustive here, and make sure that you test everything you list.

- [ ] I have tested this on real data that is reasonable and large
- [ ] If I changed the interaction with JupyterLab, I tested that it does not break other programs (like VS Code), and tested that it works "multiple times" in the same notebook.

# Documentation

Note if any new documentation needs to addressed or reviewed.

2022-11-21 14:30 UTC, naterush requested changes
Maybe bump the spacing on the column header guess -- mine inconsistently makes enough size on safari:

<img width="980" alt="Screen Shot 2022-11-21 at 9 26 25 AM" src="https://user-images.githubusercontent.com/21002431/203079430-3971529d-c4aa-4f13-8efa-a8aa059dbd68.png">

The other this is that I can't shift click on the column header resizes currently, to select a range of columns. This is not ideal. I think this is because the onClick, onMouseDown, etc stops propagation now.

So that shift+click still works on the resize for selecting a range, can we just case on if shiftKey is pressed in the onClick later in this file? E.g. if you shift + click on the column header anything, it shouldn't open anything -- this is most def just a selection change!

2022-11-21 14:30 UTC, naterush commented on mitosheet/src/components/endo/widthUtils.tsx
> +export const guessFullWidth = (sheetData: SheetData, columnIndex: number, displayColumnHeader: string): number => {
`guessFullWidthOfColumnHeaderOrContent` is a more informative name I won't wonder about in future, I think

2022-11-21 14:30 UTC, naterush commented on mitosheet/src/components/endo/widthUtils.tsx
> +export const guessFullWidth = (sheetData: SheetData, columnIndex: number, displayColumnHeader: string): number => {
E.g. much clearer, given we have functions like `getWidthData`

2022-11-21 14:30 UTC, naterush commented on mitosheet/src/components/endo/ColumnHeader.tsx
> +    const getColumnIndexesFullWidthArray = (columnIndexes: number[]): WidthData[]  => {
can we rename to `getWidthArrayAtFullWidthForColumnIndexes`

2022-11-21 14:30 UTC, naterush commented on mitosheet/src/components/endo/ColumnHeader.tsx
> +    const getColumnIndexesFullWidthArray = (columnIndexes: number[]): WidthData[]  => {
Also, I think this can go in `widthUtils.tsx` -- it doesn't need to be defined in ColumnHeader for any reason.

2022-11-21 14:30 UTC, naterush commented on mitosheet/src/components/endo/ColumnHeader.tsx
> +            const displayColumnHeader = getDisplayColumnHeader(finalColumnHeader)
I think you can just call `getDisplayColumnHeader` on this, no?

2022-11-22 19:00 UTC, aarondr77 commented
> So that shift+click still works on the resize for selecting a range, can we just case on if shiftKey is pressed in the onClick later in this file?

I didn't do this because I don't think we want you to be able to select columns on the resizer when using shift+click, but not just using click. Its inconsistent. So instead, I made the resizer smaller so that there is still space on the right hand side of the icons to click on the column. 

This is what Excel does.

2022-11-23 19:38 UTC, merged